name: Triggers
run-name: Praxis 3 Triggers!
on:
  push: # Activará el flujo de trabajo en eventos de push
    branches:
      - 'main'
      - '*'
    paths:
      - '**.js'
  pull_request: # Activará el flujo de trabajo en eventos de pull request
    types:
      - opened
      - labeled
    branches:
      - 'releases/**'
    paths:
      - '**.js'
  issues: # Activará el flujo de trabajo en eventos de issues
    types:
      - opened
      - edited
      - closed
  issue_comment: # Activará el flujo de trabajo en eventos de comentarios en issues
    types:
      - created
      - deleted
  workflow_dispatch: # Activará el flujo de trabajo cuando se invoque manualmente
    inputs:
      alerta:
        description: 'Nivel'
        required: true
        default: medio
        type: choice
        options:
          - bajo
          - medio
          - alto
      tags:
        description: 'Opcional'
        required: false
        type: boolean
      enviroment:
        description: 'Objetivo'
        required: true
        type: string
  schedule: # Activará el flujo de trabajo según una programación cron
    - cron: '30 5,17 8 * *'
jobs:
  job-t:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repo en el Runner
        uses: actions/checkout@v3
      
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Define Variable IP
        id: ip
        uses: haythem/public-ip@v1.3
        
      - name: Define Variable USERNAME   
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      
      - name: Run multi-line script
        run: |
          echo "Hello from IP: ${{ steps.ip.outputs.ipv4 }}"
          python hola-mundo.py

